#!/usr/bin/env bash

dirname=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

declare -A mon_order=(["eDP-1"]="0:eDP-1" ["VGA-0"]="1:VGA-0" ["HDMI-1"]="2:HDMI-1" ["HDMI-0"]="3:HDMI-0")

function get_mons() {
	bspc query -M --names | while read mon ; do echo ${mon_order[$mon]} ; done
}

desktop=1
initial_focus=""
last_mon=""
while read mon; 
do
	bspc monitor ${mon:2} -d $desktop; 
	if [ $desktop -eq 1 ]; then
		initial_focus=${mon:2}
	fi
	last_mon=${mon:2}
	desktop=$((desktop + 1))
done <<< $(get_mons)

bspc monitor $last_mon -a hidden
bspc monitor $initial_focus -f
