#!/usr/bin/env bash

pushd () {
    command pushd "$@" > /dev/null
}

popd () {
    command popd "$@" > /dev/null
}

pushd /home/mitch/Projects/cerv
node --trace-warnings index.js "$@"
ex=$?
popd

exit $ex
