#!/usr/bin/env bash


# Import Current Theme
source "$HOME"/.config/rofi/applets/shared/theme.bash
theme="$type/$style"

rofi -theme ${theme} -show combi -combi-modes "window,drun,run" -modes combi -display-combi "Surface App"
