#!/usr/bin/env bash

dirname=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $dirname/rofi-theme

rofi -theme ${theme} -show combi -combi-modes "window,drun,run" -modes combi -display-combi "Surface App"
