#!/bin/bash

dirname=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

handle() {
    echo $1
    case $1 in
        workspace*)
            ws=${1:11}
            $dirname/pushWorkspaceQueue.js $ws
            ls -l $dirname/state/pending/$ws \
                | awk '{print $9}' \
                | grep . \
                | while read pendingAdrs
            do
                $dirname/moveWindow.py -a $pendingAdrs -w $ws
            done
            rm -rf $dirname/state/pending/$ws
            ;;
        activewindowv2*)
            activeAdrs="0x${1:16}"
            touch $dirname/state/active/$activeAdrs
            if [ "$activeAdrs" == "$(cat $dirname/state/temp/address)" ]; then
                touch $dirname/state/temp/active
            elif [ -f $dirname/state/temp/active ]; then
                $dirname/clearTemp.py
            fi
            ;;
        changefloatingmode*)
            data="${1:20}"
            datavals=(${data//,/ })
            activeAdrs="0x${datavals[0]}"
            mode=${datavals[1]}
            if [ $mode -eq 0 ]; then
                if [ "$activeAdrs" == "$(cat $dirname/state/temp/address)" ]; then
                    rm $dirname/state/temp/*
                fi
            fi
            ;;
        closewindow*)
            activeAdrs="0x${1:13}"
            rm $dirname/state/active/$activeAdrs
            ;;
    esac
}

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock \
    | while read -r line; do handle "$line"; done
