#!/bin/bash

dirname=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

handle() {
    echo $1
    case $1 in
        workspace*)
            $dirname/pushWorkspaceQueue.js ${1:11}
            ;;
        activewindowv2*)
            activeAdrs="0x${1:16}"
            ls -l $dirname/state/temp | awk '{print $9}' | grep . | while read tempAdrs; do
                if [ "$tempAdrs" == "$activeAdrs" ]; then
                    touch $dirname/state/tempFocused/$tempAdrs
                elif [[ $dirname/state/tempFocused/$tempAdrs -nt $dirname/state/temp/$tempAdrs ]]; then
                    rm $dirname/state/temp/$tempAdrs
                    hyprctl dispatch movetoworkspacesilent special,address:$tempAdrs
                fi
            done
            ;;
        changefloatingmode*)
            data="${1:20}"
            datavals=(${data//,/ })
            activeAdrs="0x${datavals[0]}"
            mode=${datavals[1]}
            if [ $mode -eq 0 ]; then
                rm $dirname/state/temp/$activeAdrs
            fi
            ;;
    esac
}

socat -U - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
