#!/bin/bash
#
dirname=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

session_id=$1
url=$2

function ctl() {
  if [ "$session_id" == "" ]; then
    echo "$dirname/firefoxctrl.py \"$@\""
  else
    echo "$dirname/firefoxctrl.py -s $session_id \"$@\""
  fi
}

function ctl_cmd() {
  echo " [ $(ctl $@) ] "
}

function mk_stat_mod() {
  player=$1
  key=$2
  class=$3
  label=${4:-$3}
  echo sub $key $label \
    [ cmd up max $(ctl_cmd pokemon_calc_set_evs $player $class 252) \
    - cmd down min $(ctl_cmd pokemon_calc_set_evs $player $class 0) \
    - cmd return [ manual entry ] $(ctl_cmd pokemon_calc_set_evs $player $class \$\(rofi-prompt\)) \
    ]
}

function mk_pokemon_mod() {
  key=$1
  player=$2
  echo sub $key [ pokemon $2 ] \
    [ $(mk_stat_mod $player h hp) \
    - $(mk_stat_mod $player a at atk) \
    - $(mk_stat_mod $player d df def) \
    - col \
    - $(mk_stat_mod $player s sp speed) \
    - $(mk_stat_mod $player s:A sa sp.atk) \
    - $(mk_stat_mod $player s:D sd sp.def) \
    ]
}

km -m w title web \
  - cmd m "toggle tab mute" "$(ctl mute toggle)" \
  - cmd s:M "mute tab" "$(ctl mute)" \
  - cmd p "full window media" \
    "hyprctl dispatch fakefullscreen && $(ctl fw)" \
  - cmd s:P "full window media + detach" \
    "hyprctl dispatch fakefullscreen && $(ctl composite fw \| tabdetach)" \
  - col \
  - cmd n "nba stream in new tab" $(ctl_cmd tabopen \$\(openNbaStream.py\)) \
  - cmd s:N "nba stream in new window" "firefox --new-window \$(openNbaStream.py)" \
  - sub c "pokemon damage calc" \
    [ $(mk_pokemon_mod left left) \
    - col \
    - $(mk_stat_mod 1 h     hp "[ hp     left ]" ) \
    - $(mk_stat_mod 1 a     at "[ atk    left ]" ) \
    - $(mk_stat_mod 1 d     df "[ def    left ]" ) \
    - $(mk_stat_mod 1 s     sp "[ speed  left ]" ) \
    - $(mk_stat_mod 1 s:A   sa "[ sp.atk left ]" ) \
    - $(mk_stat_mod 1 s:D   sd "[ sp.def left ]" ) \
    - col \
    - $(mk_stat_mod 2 c:h   hp "[ hp     right ]" ) \
    - $(mk_stat_mod 2 ca:h  sa "[ min. hp right ]" ) \
    - $(mk_stat_mod 2 cw:h  sa "[ max. hp right ]" ) \
    - $(mk_stat_mod 2 c:a   at "[ atk    right ]" ) \
    - $(mk_stat_mod 2 ca:a  sa "[ min. atk right ]" ) \
    - $(mk_stat_mod 2 cw:a  sa "[ max. atk right ]" ) \
    - $(mk_stat_mod 2 c:d   df "[ def    right ]" ) \
    - $(mk_stat_mod 2 ca:d  sa "[ min. def right ]" ) \
    - $(mk_stat_mod 2 cw:d  sa "[ max. def right ]" ) \
    - $(mk_stat_mod 2 c:s   sp "[ speed  right ]" ) \
    - $(mk_stat_mod 2 ca:s  sa "[ min. speed right ]" ) \
    - $(mk_stat_mod 2 cw:s  sa "[ max. speed right ]" ) \
    - $(mk_stat_mod 2 cs:A  sa "[ sp.atk right ]" ) \
    - $(mk_stat_mod 2 cas:A sa "[ min. sp.atk right ]" ) \
    - $(mk_stat_mod 2 cws:A sa "[ max. sp.atk right ]" ) \
    - $(mk_stat_mod 2 cs:D  sd "[ sp.def right ]" ) \
    - $(mk_stat_mod 2 cas:D sd "[ min. sp.def right ]" ) \
    - $(mk_stat_mod 2 cws:D sd "[ max. sp.def right ]" ) \
    - col \
    - $(mk_pokemon_mod right right) \
    ] \
