#!/usr/bin/env bash

dirname=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $dirname/rofi-theme

rofi \
    -theme ${theme} \
    -show combi \
    -combi-modes "drun,run" \
    -modes combi \
    -display-combi "Open Window"
