#!/usr/bin/env bash

dirname=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $dirname/rofi-theme

# rofi \
rofi \
  -theme ${theme} \
  -matching fuzzy \
  -sorting-method fzf \
  -sort \
  -dmenu \
  "$@"
