#!/usr/bin/env bash


# Import Current Theme
source "$HOME"/.config/rofi/applets/shared/theme.bash
theme="$type/$style"

rofi \
  -theme ${theme} \
  -matching fuzzy \
  -sorting-method fzf \
  -sort \
  -dmenu \
  "$@"
