#!/usr/bin/env bash

dirname=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $dirname/modifyByPercent

function volumeGetCurr() {
    amixer get Master | grep -Po "[0-9]+(?=%)" | tail -1
}

function volumeSetNext() {
    echo "amixer sset Master unmute $1%,$1%"
    amixer sset Master unmute $1%,$1%
}

function paVolumeChanged() {
    paplay $dirname/resources/shine.quiet.wav --volume=$(( $1 * 65536 / 100 )) &
}

function modifyVolume() {
    modifyByPercent "volumeGetCurr" "volumeSetNext" "" "paVolumeChanged" $@
}

function brightnessGetCurr() {
    now=$(brightnessctl -d acpi_video0 g)
    max=$(brightnessctl -d acpi_video0 m)
    echo "100 * $now / $max" | bc -l
}

function brightnessSetNext() {
    brightnessctl -d acpi_video0 s $1%
}

function modifyBrightness() {
    # svg="/usr/share/pixmaps/tvolnoti/display-brightness-dark.svg"
    svg="/home/mitch/.config/tvolnoti/themes/dark/display_brightness.svg"
    notiArgs="-s $svg"
    modifyByPercent "brightnessGetCurr" "brightnessSetNext" "$notiArgs" ":" $@
}
