#!/usr/bin/env bash

dirname=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $dirname/util

function isMuted() {
  echo $(( (2 - $(amixer get Master | tail -2 | grep -c '\[on\]')) / 2 ))
}

amixer -D pulse sset Master toggle
if [[ $(isMuted) == 1 ]]; then
  tvolnoti-show -m
else
  curr=$(amixer get Master | grep -Po "[0-9]+(?=%)" | tail -1)
  tvolnoti-show $curr
  paVolumeChanged
fi
