#!/usr/bin/env node

const { spawn } = require('child_process');
const fs = require('fs');
const readline = require('readline');
const xdgAppPaths = require('xdg-app-paths/cjs');

const keyOnSelf = (...args) => {
    const res = {};
    args.forEach((k) => { res[k] = k; });
    return res;
};

const CMD = keyOnSelf('noop', 'render', 'done');

const crlfDelay = Infinity;
const streamLines = (input) => readline.createInterface({ input, crlfDelay });
const fileLines = (file) => streamLines(fs.createReadStream(file));

const parseActionLine = (line) => {
    try {
        return JSON.parse(line);
    } catch (e) {
        console.error(e);
        return { cmd: CMD.noop };
    }
};

const mkTmpName = (name) => {
    const pid = process.pid;
    const ts = (new Date()).getTime();
    return `/tmp/${name}-${pid}-${ts}`;
};

const mkfifo = (name="") => new Promise((fin) => {
    const fifo = mkTmpName(`ztr-${name}`);
    const proc = spawn('mkfifo', [fifo]);
    proc.on('exit', () => fin(fifo));
});

class ZtrApp {
    constructor(configDir) {
        this.configDir = configDir;
        this.nwjsProc = undefined;
        this.pid = process.pid;
        this.title = `ztr_widget_${this.pid}`;
        this.nwjsDir = `${__dirname}/ztr_nwjs`;
    }

    handleSigKill() {
        this.kill();
        process.exit(1);
    }

    async init() {
        process.on('SIGINT', () => this.handleSigKill());
        process.on('SIGQUIT', () => this.handleSigKill());
        process.on('SIGTERM', () => this.handleSigKill());
        this.fifoIn = await mkfifo("in");
        this.fofoInStream = fs.createWriteStream(this.fifoIn);
        this.fifoOut = await mkfifo("out");
        this.nwjsArgs = [this.nwjsDir, this.title, this.fifoIn, this.fifoOut];
        this.processNwjsOut();
        this.processStdIn();
    }

    async processNwjsOut() {
        for await (const _ of fileLines(this.fifoOut)) {
            const onResizeExe = `${this.configDir}/onResize`;
            spawn(onResizeExe, [this.title], { detached: true });
        }
    }

    async processStdIn() {
        for await (const line of streamLines(process.stdin)) {
            fs.appendFile(`${this.configDir}/log`, line + "\n", () => {});
            const action = parseActionLine(line);
            this.processAction(action);
        }
    }

    ensureVisible() {
        if (this.nwjsProc) { return }
        this.nwjsProc = spawn("nw", this.nwjsArgs);
    }

    kill() {
        if (!this.nwjsProc) { return; }
        this.nwjsProc.kill();
    }

    writeToNwjs(content) {
        this.fofoInStream.write(content + "\n");
    }

    processAction({ cmd, args }) {
        if (!CMD[cmd]) {
            console.error(`Unknown command [${cmd}]`);
            console.error('\t', cmd, ...args);
            return;
        }
        (({
            [CMD.noop]: () => {},
            [CMD.done]: () => { this.kill(); },
            [CMD.render]: (dom) => {
                console.log(dom);
                this.ensureVisible();
                this.writeToNwjs(JSON.stringify(dom));
            },
        })[cmd])(...args);
    }
}

const main = async() => {
    const configDir = xdgAppPaths.config();
    const app = new ZtrApp(configDir);
    app.init();
};


main();